{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-notificaties.fullname" . }}
  labels:
    {{- include "open-notificaties.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $rabbitmq_url := printf "amqp://%s:%s@%s:5672" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password .Values.settings.messageBroker.host -}}
  CELERY_BROKER_URL: {{ print $rabbitmq_url "//"  | b64enc | quote }}
  CELERY_RESULT_BACKEND: {{ .Values.settings.celery.resultBackend | b64enc | quote }}
  DB_PASSWORD: {{ .Values.settings.database.password | toString | b64enc | quote }}
  {{- if .Values.settings.email.password }}
  EMAIL_PASSWORD: {{ .Values.settings.email.password | toString | b64enc | quote }}
  {{- end }}
  PUBLISHER_BROKER_URL: {{ print $rabbitmq_url "/%2F" | b64enc | quote }}
  SECRET_KEY: {{ .Values.settings.secretKey | toString | b64enc | quote }}
  {{- if .Values.settings.sentry.dsn }}
  SENTRY_DSN: {{ .Values.settings.sentry.dsn | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.flower.enabled }}
  FLOWER_BASIC_AUTH: {{ .Values.settings.flower.basicAuth | toString | b64enc | quote }}
  {{- range $index, $index_value := .Values.flower.extraEnvVarsSecret }}
  {{ $index }}: {{ $index_value | toString | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
